---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/transactions":
    get:
      summary: List Transactions
      tags:
      - Transactions
      responses:
        '200':
          description: Transactions found
    post:
      summary: Create Expense Transaction
      tags:
      - Expense Transactions
      parameters: []
      responses:
        '201':
          description: expense transaction created
        '422':
          description: expense transaction not created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                amount:
                  type: number
                due_date:
                  type: string
                payment_method_id:
                  type: string
                category_id:
                  type: string
                paid_at:
                  type: string
              required:
              - description
              - amount
              - due_date
              - payment_method_id
              - category_id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
